# Generated by Django 3.0.8 on 2020-12-27 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('quantite', models.IntegerField(default=0)),
                ('image_present', models.ImageField(upload_to='')),
                ('prix_present', models.IntegerField()),
                ('prev_prix_present', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CategToHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70, unique=True)),
                ('adresse', models.CharField(max_length=70)),
                ('produits_fournis', models.CharField(max_length=50)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('status', models.CharField(default='Valide', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VilleLivraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscategories', to='freeshop.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='SousArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_prix', models.IntegerField(blank=True, null=True)),
                ('prix', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sousarticles', to='freeshop.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduction', models.FloatField(default=0)),
                ('debut_promotion', models.DateTimeField()),
                ('fin_promotion', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeshop.Article')),
            ],
        ),
        migrations.CreateModel(
            name='PointLivraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeshop.VilleLivraison')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeshop.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('finalisé', 'finalisé'), ('non finalisé', 'non finalisé')], default='non finalisé', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixunitaire', models.IntegerField()),
                ('quantite', models.IntegerField(default=1)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignespanier', to='freeshop.Panier')),
                ('s_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeshop.SousArticle')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('poste', models.CharField(choices=[('Administrateur du projet', 'P1'), ('Livreur', 'P2'), ('Informaticien', 'P3')], max_length=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('frais_livraison', models.IntegerField(default=0)),
                ('totalpaye', models.IntegerField(default=0)),
                ('lieu_livraison', models.CharField(blank=True, default=' ', max_length=500)),
                ('mode_paiement', models.CharField(choices=[('A la livraison', 'ALaLiv'), ('MTN MoMo', 'MTN'), ('Orange MoMo', 'OR')], default='A la livraison', max_length=60)),
                ('etat', models.CharField(choices=[('Livrée', 'Livrée'), ('En attente de livraison', 'Wait'), ('Annulée', 'Annulée')], default='En attente de livraison', max_length=50)),
                ('mode_livraison', models.CharField(choices=[('Standard', 'St'), ('Express', 'Ex'), ('Recupération par le client', 'ReClient')], default='Standard', max_length=50)),
                ('abonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freeshop.Employe')),
                ('panier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freeshop.Panier')),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristique', models.CharField(max_length=80)),
                ('valeur', models.CharField(max_length=70)),
                ('s_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristiques', to='freeshop.SousArticle')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleToHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='freeshop.Article')),
                ('categorieToHome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articlestohome', to='freeshop.CategToHome')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freeshop.Fournisseur'),
        ),
        migrations.AddField(
            model_name='article',
            name='sous_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='freeshop.SousCategorie'),
        ),
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
